# Trage hier deine Metadaten ein.
# Name und Version denkst du dir aus.
# Der Text aus dem Tooltip wird in der Hauptanwendung beim Hovern über dein Tool angezeigt.

main: org.chaoscoders.firstextension.layout.ExtensionMain
name: Zahlensysteme
version: A-1.0
tooltip: Justus Zahlensysteme
layout: org.chaoscoders.firstextension.layout